title: "Progress Report"
author: "Carolyn Jones"
date: "2024-4-17"
output: html_document
---

***I first imported 2023 Hall of Fame election data from Baseball Reference.***

```{r}
library(rvest)
library(tidyverse)
url <- "https://www.baseball-reference.com/bullpen/2023_Hall_of_Fame_Election"
html <- read_html(url)
html
```


***Next I used the SelectorGadget to extract the statistics needed for my dataset and then cleaned everything up.***

```{r}
# Get data column names and stats
table_col_names <- html %>% html_elements("table:nth-child(12) th") %>% html_text()

bbwaa <- html %>% html_elements("table:nth-child(6) td") %>% html_text()
veteran <- html %>% html_elements("table:nth-child(12) td") %>% html_text()

# Adjust stats into 4 columns and create data frames
bbwaa <- matrix(bbwaa, nrow = 5)
bbwaa <- as.data.frame(t(bbwaa))
bbwaa <- bbwaa[-c(4)]

veteran <- matrix(veteran, nrow = 4)
veteran <- as.data.frame(t(veteran))

# Rename the data frames' columns and combine into a single data set
colnames(bbwaa) <- table_col_names
colnames(veteran) <- table_col_names
stats <- rbind(bbwaa, veteran)

# Clean up results column
stats$`Result
` <- factor(stats$`Result
`) # idk why it keeps doing a new line :(
levels(stats$`Result
`) <- c("N", "N", "Y")
stats

```


```{r}
library(Lahman)
head(HallOfFame)
```

